export const SEARCH_SPECIES = "SEARCH_SPECIEST";
export const SEARCH_SPECIES_BY_ID = "SEARCH_SPECIES_BY_ID";
export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const SEARCH_SPECIES_ERROR = "SEARCH_SPECIES_ERROR";
export const SEARCH_RANDOM = "SEARCH_RANDOM";
